# Generated by Django 3.2.12 on 2022-02-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_verificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtoken",
            name="key",
            field=models.TextField(),
        ),
    ]
