# Generated by Django 3.2.12 on 2022-02-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alert_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="max_executions",
        ),
    ]
